name: Deploy Mini Flowy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Позволяет запускать workflow вручную из вкладки Actions
  workflow_dispatch:

# Устанавливает права доступа для GITHUB_TOKEN для разрешения развертывания на Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешает одновременно только одно развертывание, пропуская запуски, поставленные в очередь между уже выполняющимся и последним запуском в очереди.
# Однако НЕ отменяет выполняющиеся запуски, поскольку мы хотим, чтобы эти production развертывания завершились.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Задача сборки
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate SEO pages
        run: |
          # Обновляем BASE_URL в скрипте генерации
          sed -i "s|https://your-username.github.io/mini-flowy|https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}|g" generate-seo-pages.js
          # Генерируем SEO-страницы
          npm run build-seo
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Загружаем всю папку проекта
          path: '.'

  # Задача развертывания
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4